# ============================================================
# generate-mock-data.ps1 — Generates 00021_mock_data.sql
# Run: powershell -File scripts/generate-mock-data.ps1
# Output: supabase/migrations/00021_mock_data.sql
# ============================================================

$outFile = "D:\Projects\r6hub\supabase\migrations\00021_mock_data.sql"
$sb = [System.Text.StringBuilder]::new()

# Helper to add section
function Add($text) {
    $null = $sb.AppendLine($text)
}

Add @"
-- ============================================================
-- 00021_mock_data.sql — Large mock data set for testing
-- AUTO-GENERATED by scripts/generate-mock-data.ps1
-- DO NOT EDIT DIRECTLY — re-run the script instead
--
-- Generates: 30 profiles, 15 lobbies, 75 rounds, ~75 members,
-- ~100 bans, ~300 selections, 50 strategies, ~125 tags,
-- ~75 images, ~150 hotspots, ~100 task assignments, ~200 votes.
--
-- Uses ON CONFLICT (id) DO NOTHING for all inserts.
-- All FK references match migrations 00002 and 00008.
--
-- NOTE: profiles(id) REFERENCES auth.users(id). In local dev
-- run: SET session_replication_role = 'replica';
-- before this migration if auth.users entries don't exist.
-- ============================================================

"@

# ===================== 1. PROFILES =====================
Add "-- ============================================================"
Add "-- 1. PROFILES — 30 mock users"
Add "-- UUIDs: e1000000-0000-0000-0000-000000000001 .. 00001e"
Add "-- ============================================================"
Add "INSERT INTO profiles (id, username, avatar_url, created_at) VALUES"

$usernames = @(
    "AcePlayer", "NoScope360", "SilentKill", "PhantomX", "ShadowStrike",
    "CyberWolf", "DarkPhoenix", "FrostByte", "ThunderBolt", "NightHawk",
    "BladeRunner", "GhostRecon", "IronClad", "StormChaser", "ViperX",
    "OmegaForce", "NeonNinja", "CrimsonTide", "VoidWalker", "StarDust",
    "PixelWarrior", "QuantumRift", "EchoLocation", "ZeroGravity", "MetalGear",
    "SolarFlare", "LunarEclipse", "TitanFall", "AtomicBlast", "CyberPunk"
)

$profileRows = @()
for ($i = 0; $i -lt 30; $i++) {
    $num = $i + 1
    $days = 30 - $i
    $hex = "{0:x}" -f $num
    $uuid = "e1000000-0000-0000-0000-0000000000$($hex.PadLeft(4,'0').Substring(0,4))"
    $profileRows += "  ('$uuid', '$($usernames[$i])', NULL, NOW() - interval '$days days')"
}
Add ($profileRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 2. LOBBIES =====================
Add "-- ============================================================"
Add "-- 2. LOBBIES — 15 lobbies"
Add "-- UUIDs: e2000000-0000-0000-0000-000000000001 .. 00000f"
Add "-- ============================================================"

$lobbies = @(
    @{rc="ABC123"; lid=1; st="active"; ph="playing";  mi="a1111111-1111-1111-1111-111111111111"; ss="attacker"; hr=2},
    @{rc="XYZ789"; lid=2; st="active"; ph="playing";  mi="a2222222-2222-2222-2222-222222222222"; ss="defender"; hr=4},
    @{rc="GAMER1"; lid=3; st="active"; ph="waiting";  mi="a3333333-3333-3333-3333-333333333333"; ss="attacker"; hr=1},
    @{rc="R6HUB8"; lid=4; st="active"; ph="playing";  mi="a4444444-4444-4444-4444-444444444444"; ss="defender"; hr=6},
    @{rc="PLANT9"; lid=5; st="active"; ph="waiting";  mi="a5555555-5555-5555-5555-555555555555"; ss="attacker"; hr=0},
    @{rc="DEFUSE"; lid=6; st="active"; ph="playing";  mi="a6666666-6666-6666-6666-666666666666"; ss="defender"; hr=8},
    @{rc="SIEGEX"; lid=7; st="closed"; ph="closed";   mi="a7777777-7777-7777-7777-777777777777"; ss="attacker"; hr=72},
    @{rc="BREACH"; lid=8; st="closed"; ph="closed";   mi="a8888888-8888-8888-8888-888888888888"; ss="defender"; hr=120},
    @{rc="CLUTCH"; lid=9; st="active"; ph="playing";  mi="a1010101-1010-1010-1010-101010101010"; ss="attacker"; hr=12},
    @{rc="ROAMER"; lid=10;st="active"; ph="playing";  mi="a1111111-1111-1111-1111-111111111112"; ss="defender"; hr=10},
    @{rc="FLANK7"; lid=11;st="active"; ph="waiting";  mi="a1616161-1616-1616-1616-161616161616"; ss="attacker"; hr=0},
    @{rc="ATTACK"; lid=12;st="closed"; ph="closed";   mi="a1111111-1111-1111-1111-111111111111"; ss="defender"; hr=168},
    @{rc="VOTE44"; lid=13;st="active"; ph="playing";  mi="a3333333-3333-3333-3333-333333333333"; ss="attacker"; hr=20},
    @{rc="STRAT5"; lid=14;st="active"; ph="waiting";  mi="a5555555-5555-5555-5555-555555555555"; ss="defender"; hr=0},
    @{rc="FINAL6"; lid=15;st="active"; ph="playing";  mi="a6666666-6666-6666-6666-666666666666"; ss="attacker"; hr=3}
)

Add "INSERT INTO lobbies (id, room_code, leader_id, status, phase, map_id, starting_side, created_at, updated_at) VALUES"
$lobbyRows = @()
foreach ($l in $lobbies) {
    $lidHex = "{0:x}" -f $l.lid
    $lUuid = "e2000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    $pUuid = "e1000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    $created = if ($l.hr -eq 0) { "NOW() - interval '30 minutes'" } else { "NOW() - interval '$($l.hr) hours'" }
    $updated = if ($l.hr -eq 0) { "NOW() - interval '15 minutes'" } else { "NOW() - interval '$([math]::Max(1, $l.hr / 2)) hours'" }
    $lobbyRows += "  ('$lUuid', '$($l.rc)', '$pUuid', '$($l.st)', '$($l.ph)', '$($l.mi)', '$($l.ss)', $created, $updated)"
}
Add ($lobbyRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 3. ROUNDS =====================
Add "-- ============================================================"
Add "-- 3. ROUNDS — 5 per lobby = 75 total"
Add "-- UUIDs: e3000000-0000-0000-0000-000000000001 .. 00004b"
Add "-- ============================================================"

$roundRows = @()
$roundNum = 1
foreach ($l in $lobbies) {
    $lidHex = "{0:x}" -f $l.lid
    $lUuid = "e2000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    
    for ($r = 1; $r -le 5; $r++) {
        $rHex = "{0:x}" -f $roundNum
        $rUuid = "e3000000-0000-0000-0000-0000000000$($rHex.PadLeft(4,'0').Substring(0,4))"
        
        # team_side alternates
        if ($r % 2 -eq 1) { $side = $l.ss } else { $side = if ($l.ss -eq "attacker") { "defender" } else { "attacker" } }
        
        # status & winner_side
        if ($l.ph -eq "closed") {
            $st = "completed"
            $ws = if (Get-Random -Max 2 -Min 0) { "attacker" } else { "defender" }
        } elseif ($l.ph -eq "waiting") {
            $st = "active"
            $ws = "NULL"
        } elseif ($l.ph -eq "playing") {
            if ($r -le ($l.lid % 3 + 1)) {
                $st = "completed"
                $ws = if (Get-Random -Max 2 -Min 0) { "attacker" } else { "defender" }
            } else {
                $st = "active"
                $ws = "NULL"
            }
        }
        
        $createdOffset = $l.hr * 60 + ($r - 1) * 10
        $roundRows += "  ('$rUuid', '$lUuid', $r, '$st', '$side', $ws, NOW() - interval '$($createdOffset) minutes')"
        $roundNum++
    }
}
Add "INSERT INTO rounds (id, lobby_id, round_number, status, team_side, winner_side, created_at) VALUES"
Add ($roundRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 4. LOBBY MEMBERS =====================
Add "-- ============================================================"
Add "-- 4. LOBBY MEMBERS — 4-6 per lobby"
Add "-- UUIDs: e4000000-0000-0000-0000-000000000001 .. 00004b"
Add "-- ============================================================"

$memberCount = 1
$memberRows = @()
foreach ($l in $lobbies) {
    $lidHex = "{0:x}" -f $l.lid
    $lUuid = "e2000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    $leaderUuid = "e1000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    
    # Number of members: 4-6 based on lobby index
    $numMembers = 4 + ($l.lid % 3)
    
    # First member is leader
    $mHex = "{0:x}" -f $memberCount
    $mUuid = "e4000000-0000-0000-0000-0000000000$($mHex.PadLeft(4,'0').Substring(0,4))"
    $memberRows += "  ('$mUuid', '$lUuid', '$leaderUuid', NOW() - interval '$($l.hr * 60) minutes')"
    $memberCount++
    
    # Additional members
    for ($m = 2; $m -le $numMembers; $m++) {
        $profileIdx = ($l.lid + $m * 5) % 30
        $profileIdx = if ($profileIdx -eq 0) { 30 } else { $profileIdx }
        $pHex = "{0:x}" -f $profileIdx
        $pUuid = "e1000000-0000-0000-0000-0000000000$($pHex.PadLeft(4,'0').Substring(0,4))"
        
        $mHex = "{0:x}" -f $memberCount
        $mUuid = "e4000000-0000-0000-0000-0000000000$($mHex.PadLeft(4,'0').Substring(0,4))"
        $memberRows += "  ('$mUuid', '$lUuid', '$pUuid', NOW() - interval '$($l.hr * 60 + 5 * ($m - 1)) minutes')"
        $memberCount++
    }
}
Add "INSERT INTO lobby_members (id, lobby_id, user_id, joined_at) VALUES"
Add ($memberRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 5. LOBBY BANS =====================
Add "-- ============================================================"
Add "-- 5. LOBBY BANS — 2-3 per side per round for active lobbies"
Add "-- UUIDs: e5000000-0000-0000-0000-000000000001 .. 000064"
Add "-- ============================================================"

# Operator lists
$attOps = @()
for ($i = 1; $i -le 39; $i++) {
    $hex = "{0:x}" -f $i
    $attOps += "b$($hex.PadLeft(8,'0').Substring(0,8))-$($hex.PadLeft(8,'0').Substring(0,4))-$($hex.PadLeft(8,'0').Substring(0,4))-$($hex.PadLeft(8,'0').Substring(0,4))-$($hex.PadLeft(12,'0').Substring(0,12))"
}

$defOps = @()
for ($i = 1; $i -le 38; $i++) {
    $hex = "{0:x}" -f $i
    $defOps += "c$($hex.PadLeft(8,'0').Substring(0,8))-$($hex.PadLeft(8,'0').Substring(0,4))-$($hex.PadLeft(8,'0').Substring(0,4))-$($hex.PadLeft(8,'0').Substring(0,4))-$($hex.PadLeft(12,'0').Substring(0,12))"
}

$banRows = @()
$banCount = 1

foreach ($l in $lobbies) {
    if ($l.ph -eq "waiting") { continue }  # No bans for waiting lobbies
    
    $lidHex = "{0:x}" -f $l.lid
    $lUuid = "e2000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    
    for ($r = 1; $r -le 5; $r++) {
        # Determine round UUID
        $roundBaseNum = ($l.lid - 1) * 5 + $r
        $rHex = "{0:x}" -f $roundBaseNum
        $rUuid = "e3000000-0000-0000-0000-0000000000$($rHex.PadLeft(4,'0').Substring(0,4))"
        
        # 2-3 bans per side
        $atBans = 2 + (Get-Random % 2)
        $dfBans = 2 + (Get-Random % 2)
        
        $usedAttOps = @()
        $usedDefOps = @()
        
        for ($b = 0; $b -lt $atBans; $b++) {
            $banHex = "{0:x}" -f $banCount
            $bUuid = "e5000000-0000-0000-0000-0000000000$($banHex.PadLeft(4,'0').Substring(0,4))"
            $opIdx = $l.lid * 7 + $r * 3 + $b
            $op = $attOps[$opIdx % 39]
            if ($op -in $usedAttOps) { $op = $attOps[($opIdx + 7) % 39] }
            # Actually let's just pick a defender operator to ban from attacker side
            $defIdx = ($l.lid * 5 + $r * 7 + $b * 3) % 38
            $op = $defOps[$defIdx]
            $banRows += "  ('$bUuid', '$lUuid', '$op', 'attacker', '$rUuid', NOW() - interval '$($l.hr * 60 + $r * 8 - $b * 2) minutes')"
            $banCount++
        }
        
        for ($b = 0; $b -lt $dfBans; $b++) {
            $banHex = "{0:x}" -f $banCount
            $bUuid = "e5000000-0000-0000-0000-0000000000$($banHex.PadLeft(4,'0').Substring(0,4))"
            $attIdx = ($l.lid * 3 + $r * 5 + $b * 7) % 39
            $op = $attOps[$attIdx]
            $banRows += "  ('$bUuid', '$lUuid', '$op', 'defender', '$rUuid', NOW() - interval '$($l.hr * 60 + $r * 8 - $b * 2) minutes')"
            $banCount++
        }
    }
}

# Actually let me just write static bans to be cleaner. Using Get-Random in the generator is fine.
# But let me simplify: just write ~100 bans spread across key lobbies

# Reset
$banRows = @()
$banCount = 1

$banData = @(
    # lobby, round, attacker_bans (defender op IDs banned from attackers), defender_bans (attacker op IDs banned from defenders)
    @{l=1; r=1; a=@("c0909090-0909-0909-0909-090909090909","c0404040-0404-0404-0404-040404040404","c1010101-1010-1010-1010-101010101010"); d=@("b2828282-2828-2828-2828-282828282828","b0404040-0404-0404-0404-040404040404")},
    @{l=1; r=2; a=@("c0505050-0505-0505-0505-050505050505","c1515151-1515-1515-1515-151515151515"); d=@("b0202020-0202-0202-0202-020202020202","b2929292-2929-2929-2929-292929292929","b1414141-1414-1414-1414-141414141414")},
    @{l=1; r=3; a=@("c1212121-1212-1212-1212-121212121212","c2222222-2222-2222-2222-222222222222"); d=@("b0303030-0303-0303-0303-030303030303")},
    @{l=1; r=4; a=@("c0707070-0707-0707-0707-070707070707","c0202020-0202-0202-0202-020202020202","c1111111-1111-1111-1111-111111111111"); d=@("b0101010-0101-0101-0101-010101010101","b1717171-1717-1717-1717-171717171717")},
    @{l=1; r=5; a=@("c2626262-2626-2626-2626-262626262626","c0303030-0303-0303-0303-030303030303"); d=@("b0505050-0505-0505-0505-050505050505","b2222222-2222-2222-2222-222222222222")},
    @{l=2; r=1; a=@("c0101010-0101-0101-0101-010101010101","c1919191-1919-1919-1919-191919191919","c3232322-3232-3232-3232-323232323232"); d=@("b0303030-0303-0303-0303-030303030303","b1414141-1414-1414-1414-141414141414")},
    @{l=2; r=2; a=@("c0909090-0909-0909-0909-090909090909","c2020202-2020-2020-2020-202020202020"); d=@("b0404040-0404-0404-0404-040404040404","b2121212-2121-2121-2121-212121212121")},
    @{l=2; r=5; a=@("c1515151-1515-1515-1515-151515151515","c1616161-1616-1616-1616-161616161616","c2828282-2828-2828-2828-282828282828"); d=@("b2727272-2727-2727-2727-272727272727","b1010101-1010-1010-1010-101010101010")},
    @{l=4; r=1; a=@("c1717171-1717-1717-1717-171717171717","c1818181-1818-1818-1818-181818181818"); d=@("b2828282-2828-2828-2828-282828282828","b1111111-1111-1111-1111-111111111111")},
    @{l=4; r=2; a=@("c1313131-1313-1313-1313-131313131313","c3333332-3333-3333-3333-333333333333"); d=@("b0202020-0202-0202-0202-020202020202")},
    @{l=4; r=3; a=@("c3434342-3434-3434-3434-343434343434","c2525252-2525-2525-2525-252525252525","c2929292-2929-2929-2929-292929292929"); d=@("b1515151-1515-1515-1515-151515151515","b2222222-2222-2222-2222-222222222222")},
    @{l=6; r=1; a=@("c2323232-2323-2323-2323-232323232323","c2424242-2424-2424-2424-242424242424"); d=@("b0606060-0606-0606-0606-060606060606","b0707070-0707-0707-0707-070707070707","b0808080-0808-0808-0808-080808080808")},
    @{l=6; r=2; a=@("c0606060-0606-0606-0606-060606060606","c0808080-0808-0808-0808-080808080808"); d=@("b2626262-2626-2626-2626-262626262626","b2929292-2929-2929-2929-292929292929")},
    @{l=6; r=4; a=@("c2727272-2727-2727-2727-272727272727","c3030303-3030-3030-3030-303030303030"); d=@("b2323232-2323-2323-2323-232323232323")},
    @{l=6; r=5; a=@("c3131313-3131-3131-3131-313131313131","c3535352-3535-3535-3535-353535353535","c3636362-3636-3636-3636-363636363636"); d=@("b1818181-1818-1818-1818-181818181818","b3030303-3030-3030-3030-303030303030")},
    @{l=7; r=1; a=@("c1616161-1616-1616-1616-161616161616","c1414141-1414-1414-1414-141414141414"); d=@("b0101010-0101-0101-0101-010101010101")},
    @{l=7; r=3; a=@("c0202020-0202-0202-0202-020202020202","c0505050-0505-0505-0505-050505050505"); d=@("b1414141-1414-1414-1414-141414141414","b0303030-0303-0303-0303-030303030303")},
    @{l=8; r=1; a=@("c0303030-0303-0303-0303-030303030303","c0404040-0404-0404-0404-040404040404"); d=@("b0404040-0404-0404-0404-040404040404","b0505050-0505-0505-0505-050505050505")},
    @{l=8; r=2; a=@("c0707070-0707-0707-0707-070707070707","c0808080-0808-0808-0808-080808080808","c0909090-0909-0909-0909-090909090909"); d=@("b0606060-0606-0606-0606-060606060606")},
    @{l=8; r=4; a=@("c1010101-1010-1010-1010-101010101010","c1212121-1212-1212-1212-121212121212"); d=@("b0808080-0808-0808-0808-080808080808","b0909090-0909-0909-0909-090909090909")},
    @{l=9; r=1; a=@("c2222222-2222-2222-2222-222222222222","c2828282-2828-2828-2828-282828282828"); d=@("b1717171-1717-1717-1717-171717171717","b1919191-1919-1919-1919-191919191919")},
    @{l=9; r=2; a=@("c1515151-1515-1515-1515-151515151515","c1919191-1919-1919-1919-191919191919"); d=@("b2020202-2020-2020-2020-202020202020")},
    @{l=9; r=3; a=@("c3636362-3636-3636-3636-363636363636","c3737372-3737-3737-3737-373737373737","c3838382-3838-3838-3838-383838383838"); d=@("b2121212-2121-2121-2121-212121212121","b2323232-2323-2323-2323-232323232323")},
    @{l=10; r=1; a=@("c1111111-1111-1111-1111-111111111111","c2121212-2121-2121-2121-212121212121"); d=@("b2424242-2424-2424-2424-242424242424","b2525252-2525-2525-2525-252525252525")},
    @{l=10; r=3; a=@("c2626262-2626-2626-2626-262626262626","c0505050-0505-0505-0505-050505050505"); d=@("b2626262-2626-2626-2626-262626262626")},
    @{l=10; r=4; a=@("c0202020-0202-0202-0202-020202020202","c0909090-0909-0909-0909-090909090909","c1010101-1010-1010-1010-101010101010"); d=@("b2727272-2727-2727-2727-272727272727","b2828282-2828-2828-2828-282828282828")},
    @{l=13; r=1; a=@("c0101010-0101-0101-0101-010101010101","c0303030-0303-0303-0303-030303030303"); d=@("b2929292-2929-2929-2929-292929292929")},
    @{l=13; r=2; a=@("c3131313-3131-3131-3131-313131313131","c0606060-0606-0606-0606-060606060606"); d=@("b1616161-1616-1616-1616-161616161616","b1818181-1818-1818-1818-181818181818")},
    @{l=13; r=5; a=@("c0404040-0404-0404-0404-040404040404","c0707070-0707-0707-0707-070707070707","c0808080-0808-0808-0808-080808080808"); d=@("b0101010-0101-0101-0101-010101010101")},
    @{l=15; r=1; a=@("c2727272-2727-2727-2727-272727272727","c3737372-3737-3737-3737-373737373737"); d=@("b0303030-0303-0303-0303-030303030303","b0404040-0404-0404-0404-040404040404")},
    @{l=15; r=2; a=@("c1212121-1212-1212-1212-121212121212","c1515151-1515-1515-1515-151515151515"); d=@("b0505050-0505-0505-0505-050505050505")},
    @{l=15; r=3; a=@("c2222222-2222-2222-2222-222222222222","c2020202-2020-2020-2020-202020202020","c1919191-1919-1919-1919-191919191919"); d=@("b0606060-0606-0606-0606-060606060606","b0707070-0707-0707-0707-070707070707")},
    @{l=15; r=4; a=@("c2929292-2929-2929-2929-292929292929","c3030303-3030-3030-3030-303030303030"); d=@("b1111111-1111-1111-1111-111111111111")}
)

foreach ($ban in $banData) {
    $lidHex = "{0:x}" -f $ban.l
    $lUuid = "e2000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    $roundBaseNum = ($ban.l - 1) * 5 + $ban.r
    $rHex = "{0:x}" -f $roundBaseNum
    $rUuid = "e3000000-0000-0000-0000-0000000000$($rHex.PadLeft(4,'0').Substring(0,4))"
    
    $hrOffset = $lobbies[$ban.l - 1].hr * 60 + $ban.r * 10
    
    foreach ($op in $ban.a) {
        $bHex = "{0:x}" -f $banCount
        $bUuid = "e5000000-0000-0000-0000-0000000000$($bHex.PadLeft(4,'0').Substring(0,4))"
        $banRows += "  ('$bUuid', '$lUuid', '$op', 'attacker', '$rUuid', NOW() - interval '$hrOffset minutes')"
        $banCount++
    }
    foreach ($op in $ban.d) {
        $bHex = "{0:x}" -f $banCount
        $bUuid = "e5000000-0000-0000-0000-0000000000$($bHex.PadLeft(4,'0').Substring(0,4))"
        $banRows += "  ('$bUuid', '$lUuid', '$op', 'defender', '$rUuid', NOW() - interval '$hrOffset minutes')"
        $banCount++
    }
}

# Write bans in batches
$batchSize = 30
$totalBans = $banRows.Count
for ($i = 0; $i -lt $totalBans; $i += $batchSize) {
    $end = [math]::Min($i + $batchSize, $totalBans)
    $batch = $banRows[$i..($end-1)]
    Add "INSERT INTO lobby_bans (id, lobby_id, operator_id, side, round_id, created_at) VALUES"
    Add ($batch -join (",`n"))
    Add "ON CONFLICT (id) DO NOTHING;"
    Add ""
}

# ===================== 6. LOBBY SELECTIONS =====================
Add "-- ============================================================"
Add "-- 6. LOBBY SELECTIONS — one per member per round"
Add "-- UUIDs: e6000000-0000-0000-0000-000000000001 .. 00012c"
Add "-- ============================================================"

$selRows = @()
$selCount = 1

# Member mapping per lobby (need to track which profiles are in which lobby)
$lobbyMembers = @{}
foreach ($l in $lobbies) {
    $members = @()
    $numMembers = 4 + ($l.lid % 3)
    for ($m = 1; $m -le $numMembers; $m++) {
        $profileIdx = if ($m -eq 1) { $l.lid } else { ($l.lid + $m * 5) % 30 }
        $profileIdx = if ($profileIdx -eq 0) { 30 } else { $profileIdx }
        $members += $profileIdx
    }
    $lobbyMembers[$l.lid] = $members
}

# Site mapping per map
$mapSites = @{
    "a1111111-1111-1111-1111-111111111111" = @("d1111111-1111-1111-1111-111111111111", "d1111111-1111-1111-1111-111111111112", "d1111111-1111-1111-1111-111111111113")
    "a2222222-2222-2222-2222-222222222222" = @("d2222222-2222-2222-2222-222222222221", "d2222222-2222-2222-2222-222222222222", "d2222222-2222-2222-2222-222222222223", "d2222222-2222-2222-2222-222222222224")
    "a3333333-3333-3333-3333-333333333333" = @("d3333333-3333-3333-3333-333333333331", "d3333333-3333-3333-3333-333333333332", "d3333333-3333-3333-3333-333333333333", "d3333333-3333-3333-3333-333333333334")
    "a4444444-4444-4444-4444-444444444444" = @("d4444444-4444-4444-4444-444444444441", "d4444444-4444-4444-4444-444444444442", "d4444444-4444-4444-4444-444444444443", "d4444444-4444-4444-4444-444444444444", "d4444444-4444-4444-4444-444444444445")
    "a5555555-5555-5555-5555-555555555555" = @("d5555555-5555-5555-5555-555555555551", "d5555555-5555-5555-5555-555555555552", "d5555555-5555-5555-5555-555555555553", "d5555555-5555-5555-5555-555555555554")
    "a6666666-6666-6666-6666-666666666666" = @("d6666666-6666-6666-6666-666666666661", "d6666666-6666-6666-6666-666666666662", "d6666666-6666-6666-6666-666666666663", "d6666666-6666-6666-6666-666666666664")
    "a7777777-7777-7777-7777-777777777777" = @("d7777777-7777-7777-7777-777777777771", "d7777777-7777-7777-7777-777777777772", "d7777777-7777-7777-7777-777777777773")
    "a8888888-8888-8888-8888-888888888888" = @("d8888888-8888-8888-8888-888888888881", "d8888888-8888-8888-8888-888888888882", "d8888888-8888-8888-8888-888888888883")
    "a1010101-1010-1010-1010-101010101010" = @("d1010101-1010-1010-1010-101010101011", "d1010101-1010-1010-1010-101010101012", "d1010101-1010-1010-1010-101010101013")
    "a1111111-1111-1111-1111-111111111112" = @("d1111111-1111-1111-1111-111111111121", "d1111111-1111-1111-1111-111111111122", "d1111111-1111-1111-1111-111111111123", "d1111111-1111-1111-1111-111111111124")
    "a1616161-1616-1616-1616-161616161616" = @("d1616161-1616-1616-1616-161616161611", "d1616161-1616-1616-1616-161616161612", "d1616161-1616-1616-1616-161616161613", "d1616161-1616-1616-1616-161616161614")
}

# Round status per lobby and round for lock logic
function Get-RoundStatus($lobby, $r) {
    if ($lobby.ph -eq "closed") { return "completed" }
    if ($lobby.ph -eq "waiting") { return "active" }
    $completedUpTo = ($lobby.lid % 3 + 1)
    if ($r -le $completedUpTo) { return "completed" }
    return "active"
}

foreach ($l in $lobbies) {
    $lidHex = "{0:x}" -f $l.lid
    $lUuid = "e2000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    $members = $lobbyMembers[$l.lid]
    $sites = $mapSites[$l.mi]
    
    for ($r = 1; $r -le 5; $r++) {
        $roundBaseNum = ($l.lid - 1) * 5 + $r
        $rHex = "{0:x}" -f $roundBaseNum
        $rUuid = "e3000000-0000-0000-0000-0000000000$($rHex.PadLeft(4,'0').Substring(0,4))"
        
        # Determine team side for operator selection
        if ($r % 2 -eq 1) { $side = $l.ss } else { $side = if ($l.ss -eq "attacker") { "defender" } else { "attacker" } }
        
        $roundStatus = Get-RoundStatus $l $r
        $timeOffset = $l.hr * 60 + $r * 15
        
        foreach ($mIdx in $members) {
            $mHex = "{0:x}" -f $mIdx
            $mUuid = "e1000000-0000-0000-0000-0000000000$($mHex.PadLeft(4,'0').Substring(0,4))"
            
            # Pick a site (cycle through)
            $siteIdx = ($r + $members.IndexOf($mIdx)) % $sites.Count
            $siteId = $sites[$siteIdx]
            
            # Pick operator based on side
            $opIdx = ($l.lid * 7 + $r * 11 + $members.IndexOf($mIdx) * 13)
            if ($side -eq "attacker") {
                $op = $attOps[$opIdx % 39]
            } else {
                $op = $defOps[$opIdx % 38]
            }
            
            # Lock logic
            $locked = if ($roundStatus -eq "completed") { "NOW() - interval '$($timeOffset - 5) minutes'" } elseif ($roundStatus -eq "active" -and ($r + $mIdx) % 3 -eq 0) { "NOW() - interval '$($timeOffset - 5) minutes'" } else { "NULL" }
            
            $sHex = "{0:x}" -f $selCount
            $sUuid = "e6000000-0000-0000-0000-0000000000$($sHex.PadLeft(4,'0').Substring(0,4))"
            $selRows += "  ('$sUuid', '$lUuid', '$mUuid', '$rUuid', '$($l.mi)', '$siteId', '$op', $locked)"
            $selCount++
        }
    }
}

# Write selections in batches
$totalSel = $selRows.Count
$batchSize = 50
for ($i = 0; $i -lt $totalSel; $i += $batchSize) {
    $end = [math]::Min($i + $batchSize, $totalSel)
    $batch = $selRows[$i..($end-1)]
    Add "INSERT INTO lobby_selections (id, lobby_id, user_id, round_id, map_id, site_id, operator_id, locked_at) VALUES"
    Add ($batch -join (",`n"))
    Add "ON CONFLICT (id) DO NOTHING;"
    Add ""
}

# ===================== 7. STRATEGY TEMPLATES =====================
Add "-- ============================================================"
Add "-- 7. STRATEGY TEMPLATES — 50 new strategies across all maps"
Add "-- UUIDs: f1000000-0000-0000-0000-000000000001 .. 000032"
Add "-- ============================================================"

$strategyTemplates = @(
    # Bank (5)
    @{m="a1111111-1111-1111-1111-111111111111"; s="d1111111-1111-1111-1111-111111111111"; t="Bank CEO – Vertical Attack from Parking"; d="Ace breaches CEO wall from Parking. Buck opens floor from 2F. Nomad holds stair flank with airjabs."; img=1; att="attacker"},
    @{m="a1111111-1111-1111-1111-111111111111"; s="d1111111-1111-1111-1111-111111111112"; t="Bank Open Area – Default Plant Execute"; d="Thermite opens Open Area wall. Jackal tracks roamers in Lobby. Gridlock covers flank with trax."; img=2; att="attacker"},
    @{m="a1111111-1111-1111-1111-111111111111"; s="d1111111-1111-1111-1111-111111111113"; t="Bank Executive – Azami & Lesion Hold"; d="Azami places Kiba barriers on windows. Lesion holds stairs with gu mines. Jäger protects from frags."; img=3; att="defender"},
    @{m="a1111111-1111-1111-1111-111111111111"; s="d1111111-1111-1111-1111-111111111112"; t="Bank Staff – Mira & Maestro Defense"; d="Mira window on Staff wall. Maestro turret covers default plant. Smoke holds Open Area with canisters."; img=4; att="defender"},
    @{m="a1111111-1111-1111-1111-111111111111"; s="d1111111-1111-1111-1111-111111111111"; t="Bank CEO – Hibana Hatch Clear"; d="Hibana opens CEO hatches. Iana drones out cubby. Sledge clears floor above. Plant below hatch."; img=5; att="attacker"},
    # Border (4)
    @{m="a2222222-2222-2222-2222-222222222222"; s="d2222222-2222-2222-2222-222222222221"; t="Border Customs – Vertical Take"; d="Sledge opens floor above Customs. Nomad holds East stairs. Twitch clears gadgets. Plant default."; img=6; att="attacker"},
    @{m="a2222222-2222-2222-2222-222222222222"; s="d2222222-2222-2222-2222-222222222222"; t="Border Ventilation – Bandit & Smoke Hold"; d="Bandit tricks Ventilation wall. Smoke holds Supply with canisters. Mute jammers deny drones."; img=7; att="defender"},
    @{m="a2222222-2222-2222-2222-222222222222"; s="d2222222-2222-2222-2222-222222222223"; t="Border Armory – Hard Breach Priority"; d="Thatcher EMPs Armory wall. Thermite opens. Glaz holds angle from CCTV. Plant default."; img=8; att="attacker"},
    @{m="a2222222-2222-2222-2222-222222222222"; s="d2222222-2222-2222-2222-222222222224"; t="Border Offices – Valkyrie Intel Setup"; d="Valkyrie cams in Showers and Office. Kaid electroclaws on reinforced walls. Castle barricades doors."; img=9; att="defender"},
    # Chalet (4)
    @{m="a3333333-3333-3333-3333-333333333333"; s="d3333333-3333-3333-3333-333333333331"; t="Chalet Wine Cellar – Bandit Trick Denial"; d="Bandit tricks Wine Cellar wall. Smoke holds Bar. Jäger protects from nades. Mute denies drones."; img=10; att="defender"},
    @{m="a3333333-3333-3333-3333-333333333333"; s="d3333333-3333-3333-3333-333333333332"; t="Chalet Kitchen – Default Plant from Dining"; d="Hibana opens Kitchen hatch. Zofia clears Dining. Jackal tracks roamers in Library. Plant default."; img=11; att="attacker"},
    @{m="a3333333-3333-3333-3333-333333333333"; s="d3333333-3333-3333-3333-333333333333"; t="Chalet Master – Mira Window Control"; d="Mira window on Master wall. Lesion holds stairs. Kaid electroclaws hatches. Azami blocks windows."; img=12; att="defender"},
    @{m="a3333333-3333-3333-3333-333333333333"; s="d3333333-3333-3333-3333-333333333334"; t="Chalet Library – Vertical Attack Strategy"; d="Buck opens floor from 2F. Ace breaches Library wall. Nomad holds main stairs. Plant default."; img=13; att="attacker"},
    # Clubhouse (5)
    @{m="a4444444-4444-4444-4444-444444444444"; s="d4444444-4444-4444-4444-444444444441"; t="Clubhouse Church – Hibana & Maestro"; d="Hibana opens Church wall. Maestro turret covers default. Jäger protects. Valkyrie cam in Arsenal."; img=14; att="defender"},
    @{m="a4444444-4444-4444-4444-444444444444"; s="d4444444-4444-4444-4444-444444444442"; t="Clubhouse Cash – Standard Attack Execute"; d="Thatcher EMPs CCTV wall. Thermite opens. Sledge opens floor above Cash. Plant default."; img=15; att="attacker"},
    @{m="a4444444-4444-4444-4444-444444444444"; s="d4444444-4444-4444-4444-444444444443"; t="Clubhouse Bar – Rush Strategy"; d="Ash and Zofia double rush Bar. Ying candela clears Stock. Blitz flashes corners. Plant behind bar."; img=16; att="attacker"},
    @{m="a4444444-4444-4444-4444-444444444444"; s="d4444444-4444-4444-4444-444444444444"; t="Clubhouse Gym – Mira & Azami Hold"; d="Mira window on Gym wall. Azami blocks bedroom. Smoke holds stairs. Lesion gu on entries."; img=17; att="defender"},
    @{m="a4444444-4444-4444-4444-444444444444"; s="d4444444-4444-4444-4444-444444444445"; t="Clubhouse CCTV – Vertical Take from 3F"; d="Buck opens floor from 3F rafters. Ace breaches Cash wall. Nomad holds stairs. Plant default."; img=18; att="attacker"},
    # Coastline (4)
    @{m="a5555555-5555-5555-5555-555555555555"; s="d5555555-5555-5555-5555-555555555551"; t="Coastline Blue Bar – Penthouse Execute"; d="Ash breaches Blue Bar window. Buck opens floor from Theater. Jackal tracks in Sunrise. Plant default."; img=19; att="attacker"},
    @{m="a5555555-5555-5555-5555-555555555555"; s="d5555555-5555-5555-5555-555555555552"; t="Coastline Kitchen – Service Denial Defense"; d="Melusi Banshees on Kitchen doors. Smoke holds Service. Jäger protects. Valkyrie cam in Kitchen."; img=20; att="defender"},
    @{m="a5555555-5555-5555-5555-555555555555"; s="d5555555-5555-5555-5555-555555555553"; t="Coastline Penthouse – Theater Default Plant"; d="Hibana opens Penthouse wall. Ying candelas clear Theater. Nomad holds stairs. Plant behind couch."; img=21; att="attacker"},
    @{m="a5555555-5555-5555-5555-555555555555"; s="d5555555-5555-5555-5555-555555555554"; t="Coastline Hookah – Billiards Anti-Rush"; d="Azami Kiba on Hookah windows. Lesion traps on Billiards entries. Warden flashes counter."; img=22; att="defender"},
    # Consulate (5)
    @{m="a6666666-6666-6666-6666-666666666666"; s="d6666666-6666-6666-6666-666666666661"; t="Consulate Archives – Basement Attack"; d="Ace opens Archives wall. Zofia clears Admin. Gridlock holds stairs. Plant default behind pillar."; img=23; att="attacker"},
    @{m="a6666666-6666-6666-6666-666666666666"; s="d6666666-6666-6666-6666-666666666662"; t="Consulate Lobby – Mira & Smoke Defense"; d="Mira window on Lobby wall. Smoke holds Press Room. Jäger protects. Mute denies breaches."; img=24; att="defender"},
    @{m="a6666666-6666-6666-6666-666666666666"; s="d6666666-6666-6666-6666-666666666663"; t="Consulate Consul Office – Vertical Play"; d="Buck opens floor from 2F. Thermite breaches wall. Iana drones out Meeting. Plant default."; img=25; att="attacker"},
    @{m="a6666666-6666-6666-6666-666666666666"; s="d6666666-6666-6666-6666-666666666664"; t="Consulate Cafeteria – Kitchen Hold"; d="Azami blocks Cafeteria windows. Lesion holds Kitchen. Kaid electroclaws walls. Valkyrie cam intel."; img=26; att="defender"},
    @{m="a6666666-6666-6666-6666-666666666666"; s="d6666666-6666-6666-6666-666666666661"; t="Consulate Archives – Hibana Hatch Execute"; d="Hibana opens Archives hatches. Sledge clears above. Jackal tracks in Lobby. Plant default."; img=27; att="attacker"},
    # Emerald Plains (4)
    @{m="a7777777-7777-7777-7777-777777777777"; s="d7777777-7777-7777-7777-777777777771"; t="Emerald Plains Bar – Stock Defense Setup"; d="Mira window on Bar wall. Smoke holds Stock. Kaid electroclaws. Lesion gu on entry points."; img=28; att="defender"},
    @{m="a7777777-7777-7777-7777-777777777777"; s="d7777777-7777-7777-7777-777777777772"; t="Emerald Plains Kitchen – Default Plant Attack"; d="Thatcher EMPs Kitchen wall. Thermite opens. Gridlock holds Dining. Plant default behind counter."; img=29; att="attacker"},
    @{m="a7777777-7777-7777-7777-777777777777"; s="d7777777-7777-7777-7777-777777777773"; t="Emerald Plains Master – Roamer Clear Strategy"; d="Jackal tracks roamers in Office. Nomad holds stairs. Finka boost for entry. Plant default bedroom."; img=30; att="attacker"},
    @{m="a7777777-7777-7777-7777-777777777777"; s="d7777777-7777-7777-7777-777777777771"; t="Emerald Plains Bar – Azami & Valkyrie Hold"; d="Azami Kiba on Bar windows. Valkyrie cams in Stock. Jäger protects. Frost mats on stairs."; img=31; att="defender"},
    # Kafe (5)
    @{m="a8888888-8888-8888-8888-888888888888"; s="d8888888-8888-8888-8888-888888888881"; t="Kafe Kitchen – Bakery Default Plant"; d="Ace opens Kitchen wall. Sledge floor above. Iana drones Bakery. Plant default behind counter."; img=32; att="attacker"},
    @{m="a8888888-8888-8888-8888-888888888888"; s="d8888888-8888-8888-8888-888888888882"; t="Kafe Fireplace – Cigar Smoke Denial"; d="Smoke holds Fireplace with canisters. Mira window on Mining wall. Jäger protects. Mute denies breaches."; img=33; att="defender"},
    @{m="a8888888-8888-8888-8888-888888888888"; s="d8888888-8888-8888-8888-888888888883"; t="Kafe Cocktail – 3F Execute Strategy"; d="Hibana opens Cocktail wall. Buck vertical from roof. Nomad holds Red Stairs. Plant default."; img=34; att="attacker"},
    @{m="a8888888-8888-8888-8888-888888888888"; s="d8888888-8888-8888-8888-888888888882"; t="Kafe Fireplace – Maestro Intel Hold"; d="Maestro turret on Fireplace. Valkyrie cam in Cigar. Lesion holds Mining. Azami blocks windows."; img=35; att="defender"},
    @{m="a8888888-8888-8888-8888-888888888888"; s="d8888888-8888-8888-8888-888888888881"; t="Kafe Kitchen – Reading Room Take"; d="Thermite breaches Reading wall. Zofia clears Kitchen. Jackal tracks in Bakery. Plant default."; img=36; att="attacker"},
    # Nighthaven Labs (4)
    @{m="a1010101-1010-1010-1010-101010101010"; s="d1010101-1010-1010-1010-101010101011"; t="Nighthaven Server – Research Execute"; d="Ace opens Server wall. Iana drones Research. Nomad holds stairs. Plant behind server rack."; img=37; att="attacker"},
    @{m="a1010101-1010-1010-1010-101010101010"; s="d1010101-1010-1010-1010-101010101012"; t="Nighthaven Lobby – Operations Hold"; d="Mira window on Lobby wall. Smoke holds Operations. Kaid electroclaws. Lesion gu on entries."; img=38; att="defender"},
    @{m="a1010101-1010-1010-1010-101010101010"; s="d1010101-1010-1010-1010-101010101013"; t="Nighthaven Command – Vertical Attack"; d="Buck opens floor from 2F. Hibana breaches Command wall. Gridlock holds Control. Plant default."; img=39; att="attacker"},
    @{m="a1010101-1010-1010-1010-101010101010"; s="d1010101-1010-1010-1010-101010101012"; t="Nighthaven Lobby – Azami & Valkyrie Defense"; d="Azami blocks Lobby windows. Valkyrie cams in Operations. Jäger protects. Frost mats on stairs."; img=40; att="defender"},
    # Oregon (5)
    @{m="a1111111-1111-1111-1111-111111111112"; s="d1111111-1111-1111-1111-111111111121"; t="Oregon Basement – Laundry Mira Setup"; d="Mira window on Laundry wall. Smoke holds Supply. Bandit tricks wall. Lesion on stairs."; img=41; att="defender"},
    @{m="a1111111-1111-1111-1111-111111111112"; s="d1111111-1111-1111-1111-111111111122"; t="Oregon Kitchen – Dining Vertical Attack"; d="Sledge opens floor from 2F. Ace breaches Dining wall. Zofia clears freezer. Plant default."; img=42; att="attacker"},
    @{m="a1111111-1111-1111-1111-111111111112"; s="d1111111-1111-1111-1111-111111111123"; t="Oregon Kids – Dorms Default Plant"; d="Thatcher EMPs Kids wall. Thermite opens. Buck vertical from below. Plant behind box."; img=43; att="attacker"},
    @{m="a1111111-1111-1111-1111-111111111112"; s="d1111111-1111-1111-1111-111111111124"; t="Oregon Master – Study Attack Strategy"; d="Hibana opens Study wall. Iana drones Master. Nomad holds big tower. Plant default."; img=44; att="attacker"},
    @{m="a1111111-1111-1111-1111-111111111112"; s="d1111111-1111-1111-1111-111111111121"; t="Oregon Basement – Kaid & Mute Denial"; d="Kaid electroclaws on Laundry wall. Mute jammers on Supply. Smoke holds. Jäger protects."; img=45; att="defender"},
    # Villa (5)
    @{m="a1616161-1616-1616-1616-161616161616"; s="d1616161-1616-1616-1616-161616161611"; t="Villa Crypt – Piano Default Attack"; d="Ace opens Crypt wall. Buck vertical from above. Nomad holds stairs. Plant behind piano."; img=46; att="attacker"},
    @{m="a1616161-1616-1616-1616-161616161616"; s="d1616161-1616-1616-1616-161616161612"; t="Villa Living Room – Library Hold"; d="Mira window on Living wall. Smoke holds Library. Lesion on entries. Jäger protects."; img=47; att="defender"},
    @{m="a1616161-1616-1616-1616-161616161616"; s="d1616161-1616-1616-1616-161616161613"; t="Villa Aviator – Games Vertical Take"; d="Sledge opens floor from 2F. Hibana breaches Aviator wall. Jackal tracks roamers. Plant default."; img=48; att="attacker"},
    @{m="a1616161-1616-1616-1616-161616161616"; s="d1616161-1616-1616-1616-161616161614"; t="Villa Trophy – Statuary Execute"; d="Thermite opens Trophy wall. Thatched EMPs. Gridlock holds Art Room. Plant default."; img=49; att="attacker"},
    @{m="a1616161-1616-1616-1616-161616161616"; s="d1616161-1616-1616-1616-161616161612"; t="Villa Living Room – Azami & Maestro Hold"; d="Azami blocks Living windows. Maestro turret on Library. Valkyrie cam in Kitchen. Lesion traps."; img=50; att="defender"}
)

Add "INSERT INTO strategy_templates (id, map_id, site_id, title, description, image_url, status, created_by) VALUES"
$stratRows = @()
for ($i = 0; $i -lt $strategyTemplates.Count; $i++) {
    $st = $strategyTemplates[$i]
    $num = $i + 1
    $sHex = "{0:x}" -f $num
    $sUuid = "f1000000-0000-0000-0000-0000000000$($sHex.PadLeft(4,'0').Substring(0,4))"
    
    # created_by cycles through first 20 profiles
    $creatorIdx = ($i % 20) + 1
    $cHex = "{0:x}" -f $creatorIdx
    $cUuid = "e1000000-0000-0000-0000-0000000000$($cHex.PadLeft(4,'0').Substring(0,4))"
    
    $title = $st.t -replace "'", "''"
    $desc = $st.d -replace "'", "''"
    $imgNum = $st.img
    
    $stratRows += "  ('$sUuid', '$($st.m)', '$($st.s)', '$title', '$desc', '/images/strategies/mock_$( $imgNum.ToString('000') ).webp', 'approved', '$cUuid')"
}
Add ($stratRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 8. STRATEGY TAGS =====================
Add "-- ============================================================"
Add "-- 8. STRATEGY TAGS — 2-3 per new strategy"
Add "-- UUIDs: f2000000-0000-0000-0000-000000000001 .. 00007d"
Add "-- ============================================================"

$allTags = @("Hard Breach","Vertical","Rush","Plant","Defender","Intel","Flank Denial","Entry Fragger","Anti-Breach","Site Setup","Roamer Clear","Default Plant","Support","Area Denial","Trap","Healing","Anti-Projectile","Intel Denial","Flank Watch","Soft Breach")

$tagRows = @()
$tagCount = 1
for ($i = 0; $i -lt $strategyTemplates.Count; $i++) {
    $st = $strategyTemplates[$i]
    $num = $i + 1
    $sHex = "{0:x}" -f $num
    $sUuid = "f1000000-0000-0000-0000-0000000000$($sHex.PadLeft(4,'0').Substring(0,4))"
    
    # Determine tags based on strategy type
    $tags = @()
    if ($st.att -eq "attacker") {
        $tags += @("Plant", "Entry Fragger")
        $extraTagIdx = ($i * 3 + 1) % $allTags.Count
        $tags += $allTags[$extraTagIdx]
    } else {
        $tags += @("Defender", "Site Setup")
        $extraTagIdx = ($i * 5 + 3) % $allTags.Count
        $tags += $allTags[$extraTagIdx]
    }
    
    foreach ($tag in $tags) {
        $tHex = "{0:x}" -f $tagCount
        $tUuid = "f2000000-0000-0000-0000-0000000000$($tHex.PadLeft(4,'0').Substring(0,4))"
        $tagRows += "  ('$tUuid', '$sUuid', '$tag')"
        $tagCount++
    }
}

# Write tags in batches
$totalTags = $tagRows.Count
$batchSize = 40
for ($i = 0; $i -lt $totalTags; $i += $batchSize) {
    $end = [math]::Min($i + $batchSize, $totalTags)
    $batch = $tagRows[$i..($end-1)]
    Add "INSERT INTO strategy_tags (id, strategy_id, tag) VALUES"
    Add ($batch -join (",`n"))
    Add "ON CONFLICT (id) DO NOTHING;"
    Add ""
}

# ===================== 9. STRATEGY IMAGES =====================
Add "-- ============================================================"
Add "-- 9. STRATEGY IMAGES — 1-2 per new strategy"
Add "-- UUIDs: f3000000-0000-0000-0000-000000000001 .. 00004b"
Add "-- ============================================================"

$imgRows = @()
$imgCount = 1
for ($i = 0; $i -lt $strategyTemplates.Count; $i++) {
    $num = $i + 1
    $sHex = "{0:x}" -f $num
    $sUuid = "f1000000-0000-0000-0000-0000000000$($sHex.PadLeft(4,'0').Substring(0,4))"
    
    # 1 image for most, 2 for some
    $numImgs = if ($i % 3 -eq 0) { 2 } else { 1 }
    for ($j = 0; $j -lt $numImgs; $j++) {
        $iHex = "{0:x}" -f $imgCount
        $iUuid = "f3000000-0000-0000-0000-0000000000$($iHex.PadLeft(4,'0').Substring(0,4))"
        $imgNum = $i * 2 + $j + 1
        $imgRows += "  ('$iUuid', '$sUuid', '/images/strategies/mock_strategy_$( $imgNum.ToString('000') ).webp', $j, NULL, NOW() - interval '7 days')"
        $imgCount++
    }
}

Add "INSERT INTO strategy_images (id, strategy_id, image_url, sort_order, caption, created_at) VALUES"
Add ($imgRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 10. STRATEGY HOTSPOTS =====================
Add "-- ============================================================"
Add "-- 10. STRATEGY HOTSPOTS — 2-4 per new strategy"
Add "-- UUIDs: f4000000-0000-0000-0000-000000000001 .. 000096"
Add "-- ============================================================"

$spotLabels = @(
    @("Primary breach wall","Default plant position","Flank hold — stairs","Entry fragger rush path"),
    @("Hard breach placement","Smoke plant cover","Roamer clear rotatio","Vertical destruction point"),
    @("Gadget placement zone","Crossfire position","Rotation hole","Intel gathering spot"),
    @("Reinforcement priority","Mira window placement","Area denial point","Flank watch position"),
    @("Shield position","C4 throw line","Drone entrance","Retake path"),
    @("Jäger ADS location","Bandit trick wall","Kaid electroclaw","Mute jammer position"),
    @("Azami Kiba barrier","Smoke canister line","Lesion gu mine","Frost mat placement"),
    @("Maestro turret","Valkyrie cam spot","Echo drone hover","Mira window angle"),
    @("Banshee placement","Prisma decoy","Armor pack spot","Barbed wire chokepoint"),
    @("Default plant behind pillar","Attacker spawn peak","Droning path","Vertical hold from below")
)

$hotRows = @()
$hotCount = 1
for ($i = 0; $i -lt $strategyTemplates.Count; $i++) {
    $num = $i + 1
    $sHex = "{0:x}" -f $num
    $sUuid = "f1000000-0000-0000-0000-0000000000$($sHex.PadLeft(4,'0').Substring(0,4))"
    
    $numSpots = 2 + ($i % 3)  # 2-4 spots
    $labels = $spotLabels[$i % $spotLabels.Count]
    
    for ($j = 0; $j -lt $numSpots; $j++) {
        $hHex = "{0:x}" -f $hotCount
        $hUuid = "f4000000-0000-0000-0000-0000000000$($hHex.PadLeft(4,'0').Substring(0,4))"
        
        $xPct = 15 + ($i * 7 + $j * 13) % 75
        $yPct = 15 + ($i * 11 + $j * 17) % 75
        $label = $labels[$j % $labels.Count]
        
        $hotRows += "  ('$hUuid', '$sUuid', NULL, $xPct, $yPct, '$label')"
        $hotCount++
    }
}

Add "INSERT INTO strategy_hotspots (id, strategy_id, image_id, x_percent, y_percent, label) VALUES"
Add ($hotRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 11. TASK ASSIGNMENTS =====================
Add "-- ============================================================"
Add "-- 11. TASK ASSIGNMENTS — for active/playing lobbies"
Add "-- UUIDs: f5000000-0000-0000-0000-000000000001 .. 000064"
Add "-- ============================================================"

$taskRows = @()
$taskCount = 1
$activeLobbyIds = @(1, 2, 4, 6, 9, 10, 13, 15)

foreach ($lid in $activeLobbyIds) {
    $l = $lobbies[$lid - 1]
    $lidHex = "{0:x}" -f $lid
    $lUuid = "e2000000-0000-0000-0000-0000000000$($lidHex.PadLeft(4,'0').Substring(0,4))"
    $members = $lobbyMembers[$lid]
    
    for ($r = 1; $r -le 5; $r++) {
        $roundBaseNum = ($lid - 1) * 5 + $r
        $rHex = "{0:x}" -f $roundBaseNum
        $rUuid = "e3000000-0000-0000-0000-0000000000$($rHex.PadLeft(4,'0').Substring(0,4))"
        
        # Assign 1-2 strategies per round for some members
        $numTasks = 1 + ($r % 2)
        $usedStrats = @()
        
        for ($t = 0; $t -lt $numTasks; $t++) {
            $stratIdx = ($lid * 5 + $r * 3 + $t * 7) % 50
            if ($stratIdx -in $usedStrats) { $stratIdx = ($stratIdx + 13) % 50 }
            $usedStrats += $stratIdx
            
            $sHex2 = "{0:x}" -f ($stratIdx + 1)
            $sUuid = "f1000000-0000-0000-0000-0000000000$($sHex2.PadLeft(4,'0').Substring(0,4))"
            
            $memberIdx = $members[$t % $members.Count]
            $mHex2 = "{0:x}" -f $memberIdx
            $mUuid = "e1000000-0000-0000-0000-0000000000$($mHex2.PadLeft(4,'0').Substring(0,4))"
            
            $tHex2 = "{0:x}" -f $taskCount
            $tUuid = "f5000000-0000-0000-0000-0000000000$($tHex2.PadLeft(4,'0').Substring(0,4))"
            
            $taskRows += "  ('$tUuid', '$lUuid', '$mUuid', '$rUuid', '$sUuid', NOW() - interval '$($l.hr * 60 + $r * 15 + $t * 3) minutes')"
            $taskCount++
        }
    }
}

Add "INSERT INTO task_assignments (id, lobby_id, user_id, round_id, strategy_id, assigned_at) VALUES"
Add ($taskRows -join (",`n"))
Add "ON CONFLICT (id) DO NOTHING;"
Add ""

# ===================== 12. TASK VOTES =====================
Add "-- ============================================================"
Add "-- 12. TASK VOTES — mix of up/down on task assignments"
Add "-- UUIDs: f6000000-0000-0000-0000-000000000001 .. 0000c8"
Add "-- ============================================================"

$voteRows = @()
$voteCount = 1

# Total tasks created
$totalTasks = $taskRows.Count

for ($t = 0; $t -lt $totalTasks; $t++) {
    # Each task gets 2-4 votes from different members
    $numVotes = 2 + ($t % 3)
    $usedVoters = @()
    
    for ($v = 0; $v -lt $numVotes; $v++) {
        $voterIdx = ($t * 7 + $v * 11) % 30 + 1
        if ($voterIdx -in $usedVoters) { $voterIdx = ($voterIdx + 5) % 30 + 1 }
        $usedVoters += $voterIdx
        
        $vHex = "{0:x}" -f $voterIdx
        $vUuid = "e1000000-0000-0000-0000-0000000000$($vHex.PadLeft(4,'0').Substring(0,4))"
        
        # Task assignment UUID
        $taskNum = $t + 1
        $tHex3 = "{0:x}" -f $taskNum
        $taskUuid = "f5000000-0000-0000-0000-0000000000$($tHex3.PadLeft(4,'0').Substring(0,4))"
        
        $voteType = if (($t + $v) % 3 -eq 0) { "down" } else { "up" }
        
        $vHex2 = "{0:x}" -f $voteCount
        $voteUuid = "f6000000-0000-0000-0000-0000000000$($vHex2.PadLeft(4,'0').Substring(0,4))"
        
        $voteRows += "  ('$voteUuid', '$taskUuid', '$vUuid', '$voteType', NOW() - interval '$((7 * 24 - $t) % 168) hours')"
        $voteCount++
    }
}

# Write votes in batches
$totalVotes = $voteRows.Count
$batchSize = 50
for ($i = 0; $i -lt $totalVotes; $i += $batchSize) {
    $end = [math]::Min($i + $batchSize, $totalVotes)
    $batch = $voteRows[$i..($end-1)]
    Add "INSERT INTO task_votes (id, task_assignment_id, user_id, vote_type, created_at) VALUES"
    Add ($batch -join (",`n"))
    Add "ON CONFLICT (id) DO NOTHING;"
    Add ""
}

# Write the file
$content = $sb.ToString()
[System.IO.File]::WriteAllText($outFile, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "Generated: $outFile"
Write-Host "File size: $((Get-Item $outFile).Length) bytes"
Write-Host "Row counts:"
Write-Host "  Profiles: 30"
Write-Host "  Lobbies: $($lobbies.Count)"
Write-Host "  Rounds: $($roundRows.Count)"
Write-Host "  Members: $($memberRows.Count)"
Write-Host "  Bans: $($banRows.Count)"
Write-Host "  Selections: $($selRows.Count)"
Write-Host "  Strategies: $($strategyTemplates.Count)"
Write-Host "  Tags: $($tagRows.Count)"
Write-Host "  Images: $($imgRows.Count)"
Write-Host "  Hotspots: $($hotRows.Count)"
Write-Host "  Task Assignments: $($taskRows.Count)"
Write-Host "  Task Votes: $($voteRows.Count)"
