#Requires -Version 5.1
<#
.SYNOPSIS
    Setup Supabase self-hosted for relay - first-time setup.
.DESCRIPTION
    1. Generates random secrets (POSTGRES_PASSWORD, JWT_SECRET, etc.)
    2. Generates valid JWT anon/service_role keys
    3. Writes .env.supabase
    4. Starts docker compose
    5. Waits for PostgreSQL ready
    6. Applies all migrations from supabase/migrations/
    7. Verifies connection
#>

param(
    [switch]$SkipSecrets,
    [switch]$SkipMigrations
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $ProjectRoot ".env.supabase"
$MigrationsDir = Join-Path $ProjectRoot "supabase\migrations"

function Write-Step($msg) { Write-Host "`n>> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "   OK: $msg" -ForegroundColor Green }
function Write-Err($msg)  { Write-Host "   FAIL: $msg" -ForegroundColor Red; exit 1 }

# ─── Generate Secrets ───────────────────────────────────────
if (-not $SkipSecrets) {
    Write-Step "Generating secrets"

    $postgresPassword = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 48 | ForEach-Object { [char]$_ })
    $jwtSecret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 64 | ForEach-Object { [char]$_ })
    $secretKeyBase = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 64 | ForEach-Object { [char]$_ })
    $pgMetaCryptoKey = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object { [char]$_ })
    $dashboardPassword = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 24 | ForEach-Object { [char]$_ })

    Write-Ok "POSTGRES_PASSWORD generated ($($postgresPassword.Length) chars)"
    Write-Ok "JWT_SECRET generated ($($jwtSecret.Length) chars)"

    # ─── Generate JWT Keys ──────────────────────────────────
    Write-Step "Generating JWT API keys"

    function ConvertTo-Base64Url([string]$text) {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($text)
        return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    }

    function New-JwtKey([string]$role) {
        $header = '{"alg":"HS256","typ":"JWT"}'
        $iat = [int][double]::Parse((Get-Date -UFormat %s))
        $exp = $iat + (10 * 365 * 24 * 3600)  # 10 years
        $payload = @"
{
  "role": "$role",
  "iss": "supabase-demo",
  "iat": $iat,
  "exp": $exp
}
"@
        $headerB64 = ConvertTo-Base64Url $header
        $payloadB64 = ConvertTo-Base64Url $payload
        $signingInput = "$headerB64.$payloadB64"

        $hmac = New-Object System.Security.Cryptography.HMACSHA256
        $hmac.Key = [System.Text.Encoding]::UTF8.GetBytes($jwtSecret)
        $hash = $hmac.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($signingInput))
        $signature = [Convert]::ToBase64String($hash).TrimEnd('=').Replace('+', '-').Replace('/', '_')

        return "$signingInput.$signature"
    }

    $anonKey = New-JwtKey "anon"
    $serviceRoleKey = New-JwtKey "service_role"
    Write-Ok "ANON_KEY generated"
    Write-Ok "SERVICE_ROLE_KEY generated"

    # ─── Write .env.supabase ────────────────────────────────
    Write-Step "Writing .env.supabase"

    $envContent = @"
# relay - Supabase Self-Hosted Configuration
# Generated by setup-supabase.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# Re-run with -SkipSecrets to keep current secrets.

# Ports
KONG_HTTP_PORT=54321
KONG_HTTPS_PORT=54323
STUDIO_PORT=54322
POSTGRES_DIRECT_PORT=54324
MAILPIT_SMTP_PORT=1025
MAILPIT_UI_PORT=8025

# Postgres
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432
POSTGRES_PASSWORD=$postgresPassword

# JWT
JWT_SECRET=$jwtSecret
JWT_EXPIRY=3600
ANON_KEY=$anonKey
SERVICE_ROLE_KEY=$serviceRoleKey

# Dashboard
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=$dashboardPassword

# Secrets
SECRET_KEY_BASE=$secretKeyBase
PG_META_CRYPTO_KEY=$pgMetaCryptoKey

# URLs
SUPABASE_PUBLIC_URL=http://localhost:54321
API_EXTERNAL_URL=http://localhost:54321

# Auth
SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=http://localhost:3000/**
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

# Mailer (Mailpit)
SMTP_ADMIN_EMAIL=admin@localhost
SMTP_HOST=mailpit
SMTP_PORT=1025
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=relay-Dev
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify

# Storage
GLOBAL_S3_BUCKET=stub
REGION=stub
STORAGE_TENANT_ID=stub
S3_PROTOCOL_ACCESS_KEY_ID=625729a08b95bf1b7ff351a663f3a23c
S3_PROTOCOL_ACCESS_KEY_SECRET=850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907

# PostgREST
PGRST_DB_SCHEMAS=public,storage,graphql_public
PGRST_DB_MAX_ROWS=1000
PGRST_DB_EXTRA_SEARCH_PATH=public

# Studio
STUDIO_DEFAULT_ORGANIZATION=relay
STUDIO_DEFAULT_PROJECT=relay-Local

# ImgProxy
IMGPROXY_AUTO_WEBP=true
"@

    Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
    Write-Ok ".env.supabase written"

    # ─── Update .env.local for Next.js ──────────────────────
    Write-Step "Updating .env.local with local Supabase keys"
    $envLocalPath = Join-Path $ProjectRoot ".env.local"
    $envLocalContent = @"
# Supabase (local self-hosted)
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anonKey
SUPABASE_SERVICE_ROLE_KEY=$serviceRoleKey

# Discord
DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/your-webhook-id/your-webhook-token

# Validation
VALIDATION_HMAC_SECRET=***REDACTED***
"@
    # Backup existing .env.local
    if (Test-Path $envLocalPath) {
        $backup = "$envLocalPath.bak-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        Copy-Item $envLocalPath $backup
        Write-Ok "Backed up .env.local -> $backup"
    }
    Set-Content -Path $envLocalPath -Value $envLocalContent -Encoding UTF8
    Write-Ok ".env.local updated with local keys"
}

# ─── Validate env file exists ───────────────────────────────
if (-not (Test-Path $EnvFile)) {
    Write-Err ".env.supabase not found. Run without -SkipSecrets first."
}

# ─── Start Docker Compose ───────────────────────────────────
Write-Step "Starting Docker Compose"
Push-Location $ProjectRoot
try {
    docker compose --env-file .env.supabase up -d
    if ($LASTEXITCODE -ne 0) { Write-Err "docker compose up failed" }
    Write-Ok "Containers starting"
} finally {
    Pop-Location
}

# ─── Wait for PostgreSQL ────────────────────────────────────
Write-Step "Waiting for PostgreSQL (up to 60s)"
$maxWait = 60
$elapsed = 0
$pgReady = $false
while ($elapsed -lt $maxWait) {
    $result = docker exec supabase-db pg_isready -U postgres -h localhost 2>&1
    if ($LASTEXITCODE -eq 0) {
        $pgReady = $true
        break
    }
    Start-Sleep -Seconds 2
    $elapsed += 2
    Write-Host "   ... waiting ($elapsed s)" -ForegroundColor Yellow
}
if (-not $pgReady) { Write-Err "PostgreSQL not ready after ${maxWait}s" }
Write-Ok "PostgreSQL is ready"

# ─── Apply Migrations ───────────────────────────────────────
if (-not $SkipMigrations) {
    Write-Step "Applying migrations"
    & (Join-Path $PSScriptRoot "apply-migrations.ps1")
}

# ─── Summary ────────────────────────────────────────────────
Write-Host "`n" -NoNewline
Write-Host "=== Supabase Local Ready ===" -ForegroundColor Green
Write-Host "  Kong API:     http://localhost:54321" -ForegroundColor White
Write-Host "  Studio UI:    http://localhost:54322" -ForegroundColor White
Write-Host "  Postgres:     localhost:54324" -ForegroundColor White
Write-Host "  Mailpit UI:   http://localhost:8025" -ForegroundColor White
Write-Host "  Dashboard:    supabase / $dashboardPassword" -ForegroundColor White
Write-Host ""
Write-Host "  Next.js .env.local updated with local keys." -ForegroundColor Yellow
Write-Host "  Run 'docker compose --env-file .env.supabase down' to stop." -ForegroundColor Yellow
